[main]
# These are pointless
exclude=kernel-debug* setroubleshoot setroubleshoot-plugins setroubleshoot-server initial-setup* dracut-config-rescue  sssd* deltarpm tcpdump traceroute dos2unix ed sos time rsyslog* chrony at pinfo plocate bc abrt-cli crontabs psacct cyrus-sasl-plain realmd iptstate mcelog mtr rsyslog
