[main]
exclude=valent-devel kernel-debug* setroubleshoot setroubleshoot-plugins setroubleshoot-server initial-setup* dracut-config-rescue sssd* deltarpm tcpdump traceroute dos2unix sos rsyslog* chrony at pinfo plocate bc abrt-cli crontabs psacct cyrus-sasl-plain realmd iptstate mcelog mtr rsyslog
