[Config]
MinimumVersion=26~devel
Profiles=bootc-ostree,fedora-bootc-ostree

[Distribution]
Distribution=fedora
Release=44

[Build]
ToolsTree=default
History=yes
CacheDirectory=mkosi.cache
Incremental=yes

[Validation]
SecureBoot=no
SignExpectedPcr=no

[Runtime]
RuntimeSize=30G
RAM=4G
CPUs=4

[Output]
ImageId=Taxifolia
