[Match]
Distribution=fedora

# These were manually picked out from a Bluefin comparison with `rpm -qa --qf="%{NAME}\n" `
[Content]
WithRecommends=True
RemovePackages=
    greenboot
    appstream-data

Packages=
  alsa-firmware
  alsa-sof-firmware
  alsa-tools-firmware
  alsa-ucm
  alsa-utils
  atheros-firmware
  audispd-plugins
  brcmfmac-firmware
  cifs-utils
  cups
  cups-pk-helper
  dymo-cups-drivers
  fprintd
  fprintd-pam
  fuse
  fuse-common
  fwupd
  gstreamer1-plugin-dav1d
  gstreamer1-plugin-openh264
  gum
  gvfs-archive
  gvfs-mtp
  gvfs-nfs
  gvfs-smb
  hplip
  hyperv-daemons
  ibus
  ifuse
  intel-audio-firmware
  iwlegacy-firmware
  iwlwifi-dvm-firmware
  iwlwifi-mvm-firmware
  jmtpfs
  kernel-modules-extra
  libcamera-gstreamer
  libcamera-tools
  libcamera-v4l2
  libimobiledevice
  libimobiledevice-utils
  libratbag-ratbagd
  man-pages
  mesa-libGLU
  mobile-broadband-provider-info
  mt7xxx-firmware
  NetworkManager
  NetworkManager-adsl
  NetworkManager-bluetooth
  NetworkManager-config-connectivity-fedora
  NetworkManager-libnm
  NetworkManager-openconnect
  NetworkManager-openvpn
  NetworkManager-ssh
  NetworkManager-ssh-selinux
  NetworkManager-strongswan
  NetworkManager-vpnc
  NetworkManager-wifi
  NetworkManager-wwan
  nxpwireless-firmware
  openconnect
  open-vm-tools
  open-vm-tools-desktop
  pam_yubico
  pcsc-lite
  pipewire-config-raop
  pipewire-gstreamer
  pipewire-utils
  plymouth
  plymouth-system-theme
  printer-driver-brlaser
  ptouch-driver
  qemu-guest-agent
  realtek-firmware
  rsync
  spice-vdagent
  steam-devices
  switcheroo-control
  system-config-printer-libs
  system-config-printer-udev
  tiwilink-firmware
  tuned
  tuned-ppd
  udisks2-lvm2
  unzip
  usb_modeswitch
  uxplay
  vpnc
  whois
  wireguard-tools
  xdg-user-dirs
  zram-generator-defaults
