# https://gitlab.com/redhat/centos-stream/containers/bootc/-/blob/c${CENTOS_VERSION}s/edge/manifest.yaml?ref_type=heads
[Content]
WithRecommends=true

VolatilePackages=
    systemd-container

Packages=
    alsa-firmware
    alsa-sof-firmware
    alsa-tools-firmware
    amd-gpu-firmware
    attr
    audit-libs
    audit-rules
    containers-common
    container-selinux
    @core
    criu
    criu-libs
    crun
    efibootmgr
    flatpak-session-helper
    git-core
    glibc-minimal-langpack
    iproute-tc
    iptables-nft
    jq
    kernel
    kernel-core
    keyutils
    kmod
    libselinux
    libsemanage
    linux-firmware
    logrotate
    lsof
    lvm2
    nftables
    ntpd-rs
    nvme-cli
    openssl
    p11-kit-server
    pam
    passwd
    podman
    polkit
    python3
    rpm-plugin-selinux
    socat
    stalld
    @standard
    tzdata
    xfsprogs
    xz
    zlib
    zstd
