[Match]
Distribution=fedora

[Build]
SandboxTrees=../../repos/nvidia-container-toolkit.repo:/etc/yum.repos.d/nvidia-container-toolkit.repo

[Distribution]
Repositories=nvidia-container-toolkit

[Content]
Packages=
    nvidia-container-toolkit
