[Match]
Distribution=fedora

[Build]
SandboxTrees=../../repos/terra-nvidia.repo:/etc/yum.repos.d/terra-nvidia.repo

[Distribution]
Repositories=terra-nvidia

[Content]
RemovePackages=akmod-nvidia
Packages=
    dkms
    gcc-c++
    libnvidia-fbc
    libva-nvidia-driver
    nvidia-container-toolkit
    nvidia-driver
    nvidia-driver-cuda
    nvidia-modprobe
    nvidia-persistenced
    nvidia-settings
