[Match]
Distribution=fedora

[Build]
SandboxTrees=../../repos/terra-nvidia.repo:/etc/yum.repos.d/terra-nvidia.repo

[Distribution]
Repositories=terra-nvidia

[Content]
Packages=
    nvidia-container-toolkit
