[Match]
Distribution=fedora
Architecture=arm64

[Build]
SandboxTrees=repos/fedora-asahi-remix-hotfixes.repo:/etc/yum.repos.d/fedora-asahi-remix-hotfixes.repo

[Distribution]
Repositories=fedora-asahi-remix-hotfixes
Repositories=copr:copr.fedorainfracloud.org:group_asahi:fedora-remix-branding
Repositories=copr:copr.fedorainfracloud.org:group_asahi:fedora-remix-scripts
Repositories=copr:copr.fedorainfracloud.org:group_asahi:kernel
Repositories=copr:copr.fedorainfracloud.org:group_asahi:mesa
Repositories=copr:copr.fedorainfracloud.org:group_asahi:u-boot

[Content]
Packages=
    alsa-ucm-asahi
    asahi-platform-metapackage
    asahi-repos
    fedora-asahi-remix-scripts
    tiny-dfr
    grub2-efi-aa64-modules
    uboot-images-armv8
    asahi-fwupdate
    dracut-asahi
    update-m1n1
    aajohan-comfortaa-fonts
