[Match]
Distribution=fedora

[Build]
SandboxTrees=repos/avengemedia-danklinux.repo:/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:avengemedia:danklinux.repo
SandboxTrees=repos/avengemedia-dms-git.repo:/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:avengemedia:dms-git.repo

[Distribution]
Repositories=copr:copr.fedorainfracloud.org:avengemedia:danklinux
Repositories=copr:copr.fedorainfracloud.org:avengemedia:dms-git

[Content]
WithRecommends=false
Packages=
    dms
    dms-cli
    dms-greeter
    dgop
    dsearch

