[Match]
Distribution=fedora

[Distribution]
Repositories=copr:copr.fedorainfracloud.org:avengemedia:danklinux
Repositories=copr:copr.fedorainfracloud.org:avengemedia:dms-git

[Content]
WithRecommends=false
Packages=
    dms
    dms-cli
    dms-greeter
    dgop
    dsearch
    quickshell-git

