[Match]
Distribution=fedora

[Build]
SandboxTrees=repos/yalter-niri-git.repo:/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:yalter:niri-git.repo

[Distribution]
Repositories=copr:copr.fedorainfracloud.org:yalter:niri-git

[Content]
# https://github.com/niri-wm/niri/issues/2734
RemoveFiles=
    /usr/share/doc/niri
WithRecommends=false
WithDocs=false
Packages=niri
