[Match]
Distribution=fedora

# `just` breaks OSTree due to chinese character on file name
[Content]
WithRecommends=false
Packages=
    just
    kf6-kimageformats
    kf6-kirigami
    kf6-qqc2-desktop-style
    plasma-breeze
