[Match]
Distribution=fedora

[Build]
SandboxTrees=repos/terra.repo:/etc/yum.repos.d/terra.repo

[Distribution]
Repositories=terra

[Content]
WithRecommends=false
Packages=
    terra-release
    terra-release-extras
    maple-fonts
    xdg-terminal-exec-nautilus
    iio-niri
    valent
