[Match]
Distribution=fedora

[Build]
ExtraTrees=
    cosign.pub:/usr/share/pki/containers/zirconium.pub
    assets/wallpapers:/usr/share/zirconium/skel/Pictures/Wallpapers
    assets/logos/logo-z.svg:/usr/share/zirconium/pixmaps/logo-z.svg
    assets/logos/watermark.png:/usr/share/plymouth/themes/spinner/watermark.png

[Content]
Packages=
    brightnessctl
    cava
    chezmoi
    ddcutil
    default-fonts
    default-fonts-core-emoji
    fastfetch
    fcitx5-mozc
    flatpak
    foot
    fpaste
    fzf
    gcr
    git-core
    glibc-all-langpacks
    glycin-thumbnailer
    gnome-disk-utility
    gnome-keyring
    gnome-keyring-pam
    gnupg2-scdaemon
    google-noto-color-emoji-fonts
    google-noto-emoji-fonts
    greetd
    greetd-selinux
    gst-thumbnailers
    hyfetch
    input-remapper
    just
    kf6-kimageformats
    kf6-kirigami
    kf6-qqc2-desktop-style
    khal
    nautilus
    nautilus-python
    openssh-askpass
    orca
    pipewire
    plasma-breeze
    playerctl
    qt6ct
    qt6-qtmultimedia
    steam-devices
    tailscale
    udiskie
    webp-pixbuf-loader
    wireplumber
    wl-clipboard
    wl-mirror
    wtype
    xdg-desktop-portal-gnome
    xdg-desktop-portal-gtk
    xdg-terminal-exec
    xdg-user-dirs
    xwayland-satellite
    ykman
