[Match]
Distribution=fedora

[Content]
ExtraTrees=
    subprojects/ublue-brew/system_files:/
    subprojects/bluefin-common/system_files/shared/usr/bin/luks*:/usr/bin
    subprojects/bluefin-common/system_files/shared/:/usr/share/ublue-os/just:/usr/share/ublue-os/just
