[Match]
Distribution=fedora

[Build]
SandboxTrees=repos/ublue-os-packages.repo:/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:ublue-os:packages.repo

[Distribution]
Repositories=copr:copr.fedorainfracloud.org:ublue-os:packages

[Content]
WithRecommends=false
Packages=uupd
