[Match]
Distribution=fedora

[Build]
SandboxTrees=repos/zirconium-packages.repo:/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:zirconium:packages.repo

[Distribution]
Repositories=copr:copr.fedorainfracloud.org:zirconium:packages

[Content]
Packages=
    iio-niri
    valent-git
