# This profile attempts to replicate what quay.io/fedora/fedora-bootc:latest does.
# This is also specific to zirconium. This might not have things you want.
[Match]
Profiles=fedora-bootc-ostree
Distribution=fedora

