# This profile attempts to replicate what quay.io/fedora/fedora-bootc:latest does.
[Match]
Profiles=bootc-ostree
Distribution=fedora

[Content]
RemoveFiles=
    /usr/etc
    /var/
    /boot/*

Packages=
    bootc
    bootupd
    rpm-ostree
    ostree

[Build]
ToolsTreePackages=ostree

[Content]
# We want to use the bootc/ostree dracut modules instead of letting mkosi handle this. Please reconsider once arbitrary content can be added to the initramfs somehow
Bootable=no
KernelCommandLine=

[Output]
OciLabels=containers.bootc=1
Format=oci
