# THIS PROFILE SHOULD NOT BE USED BY DEFAULT
# This is an implementation of sysupdate-based zirconium, everything that would be necessary to implement the same idea as systemd's particleOS.
# Nothing bootc-specific or bootc native should be here.

[Match]
Profiles=sysupdate

[Output]
SplitArtifacts=uki,partitions
Format=disk

[Content]
UnifiedKernelImageFormat=%i_%v_%a
InitrdProfiles=
KernelInitrdModules=default
KernelCommandLine=
    root=dissect
    mount.usr=dissect
    rw
    audit=0
    systemd.image_policy=esp=unprotected:xbootldr=unprotected+unused+absent:usr=signed:root=unprotected+absent:swap=encrypted+unused+absent:home=unprotected+absent:=ignore
    systemd.image_filter=usr=Zirconium_*:usr-verity=Zirconium_*:usr-verity-sig=Zirconium_*:root=Zirconium-*:swap=Zirconium-*:home=Zirconium-*
    systemd.debug-shell=ttyS0
    rd.systemd.debug-shell=ttyS0
    ipe.enforce=0

VolatilePackages=
    systemd-boot

InitrdVolatilePackages=
    systemd
    udev

[Validation]
SecureBoot=yes
SignExpectedPcr=yes

# mkosi vm specific
[Runtime]
RuntimeSize=40G
RAM=4G
CPUs=4
Ephemeral=yes
Credentials=
    passwd.plaintext-password.root=particleos
    tty.serial.hvc0.agetty.autologin=particleos
    tty.serial.hvc0.login.noauth=yes
    tty.console.agetty.autologin=particleos
    tty.console.login.noauth=yes
    tty.virtual.tty1.agetty.autologin=particleos
    tty.virtual.tty1.login.noauth=yes
