[Match]
Distribution=fedora

[Build]
SandboxTrees=../../repos/bieszczaders-kernel-cachyos.repo:/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:bieszczaders:kernel-cachyos.repo

[Distribution]
Repositories=copr:copr.fedorainfracloud.org:bieszczaders:kernel-cachyos

[Content]
Packages=
    kernel-cachyos
    kernel-cachyos-devel

RemovePackages=
    kernel-core
    kernel-devel
    kernel-modules-core
