[Match]
Distribution=fedora

[Build]
SandboxTrees=../../repos/lizardbyte-beta.repo:/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:lizardbyte:beta.repo

[Distribution]
Repositories=copr:copr.fedorainfracloud.org:lizardbyte:beta

[Content]
Packages=
    Sunshine
