[Match]
Distribution=fedora

[Build]
SandboxTrees=../../repos/terra-mesa.repo:/etc/yum.repos.d/terra-mesa.repo

[Distribution]
Repositories=terra-mesa

[Content]
RemovePackages=
    mesa-va-drivers

Packages=
    mesa-dri-drivers
    mesa-filesystem
    mesa-libEGL
    mesa-libgbm
    mesa-libGL
    mesa-vulkan-drivers
    terra-release-mesa
