[Match]
Distribution=fedora

[Build]
SandboxTrees=../../repos/terra-extras.repo:/etc/yum.repos.d/terra-extras.repo

[Distribution]
Repositories=terra-extras

[Content]
Packages=
    terra-release-extras
    terra-gamescope

