[Content]
ExtraTrees=
    ../../../../subprojects/valve-hw-audio/ucm2/conf.d/sof-nau8821-max:/usr/share/alsa/ucm2/conf.d/sof-nau8821-max
    ../../../../subprojects/valve-hw-audio/sof_fw/sof:/usr/lib/firmware/amd/sof
    ../../../../subprojects/valve-hw-audio/sof_fw/sof-tplg:/usr/lib/firmware/amd/sof-tplg
