[Distribution]
Repositories=terra

[Content]
RemoveFiles=
    /usr/share/wayland-sessions/gamescope-session-steam.desktop

Packages=
    asusctl
    dkms-xonedo-nightly
    gamescope-session-plus
    gamescope-session-steam
    inputplumber
    powerbuttond
    powerstation
    ScopeBuddy
    scx-scheds
    scx-tools
    steam
    steam-notif-daemon
    steamos-manager
    steamos-manager-gamescope-session-plus
    umu-launcher
