[Match]
Distribution=fedora

[Content]
Packages=
    grub2-common
    grub2-efi-x64
    grub2-efi-x64-cdboot
    grub2-efi-x64-modules
    grub2-pc
    grub2-pc-modules
    shim
    grub2-tools-minimal
    bootupd
