[Match]
Distribution=fedora

# Extra things I didnt find in the quay.io/fedora/fedora-bootc manifests
[Content]
WithRecommends=true
Packages=
    dnf5
    dnf5-plugins
    dracut-network
    dracut-squash
    efibootmgr
    flatpak-session-helper
    irqbalance
    man-db
    nfs-utils
    p11-kit-server
    WALinuxAgent-udev
