[Match]
Distribution=fedora

# https://gitlab.com/redhat/centos-stream/containers/bootc/-/blob/c${CENTOS_VERSION}s/edge/manifest.yaml?ref_type=heads
[Content]
WithRecommends=true
VolatilePackages=
    systemd
    systemd-udev

Packages=
    alsa-firmware
    alsa-sof-firmware
    alsa-tools-firmware
    amd-gpu-firmware
    audit
    audit-libs
    audit-rules
    basesystem
    bash
    containers-common
    container-selinux
    coreutils
    cryptsetup
    dbus
    dracut
    e2fsprogs
    firewalld
    firewalld
    git-core
    glibc
    glibc-minimal-langpack
    greenboot
    iproute
    iputils
    kernel
    kernel-core
    keyutils
    kmod
    less
    libselinux
    libsemanage
    linux-firmware
    openssh-clients
    openssh-server
    openssl
    pam
    podman
    policycoreutils
    polkit
    procps-ng
    python3
    rpm
    selinux-policy-targeted
    shadow-utils
    tar
    tpm2-tools
    tzdata
    util-linux
    xz
    zlib
