[Distribution]
Repositories=fedora-nvidia

[Content]
Packages=
    dkms
    gcc-c++
    libnvidia-fbc
    libva-nvidia-driver
    nvidia-driver
    nvidia-driver-cuda
    nvidia-modprobe
    nvidia-persistenced
    nvidia-settings
