[Distribution]
Repositories=copr:copr.fedorainfracloud.org:avengemedia:danklinux
Repositories=copr:copr.fedorainfracloud.org:avengemedia:dms-git

[Content]
Packages=
    dms
    dms-cli
    dms-greeter
    dgop
    dsearch
    quickshell-git
    dankcalendar-git
    dsearch
