# Temporary config to address https://github.com/Supreeeme/xwayland-satellite/issues/468

[Match]
Architecture=arm64

[Content]
Packages=
    https://kojipkgs.fedoraproject.org//packages/xwayland-satellite/0.8.1/1.fc44/aarch64/xwayland-satellite-0.8.1-1.fc44.aarch64.rpm
