# Specifically for LiveISOs
[Match]
Profiles=liveiso
Distribution=fedora

[Content]
# We don't want initrams generation from systemd, nothing!
Bootable=no

[Output]
# isobuild's root is a chroot
Format=directory
