# Specifically for LiveISOs
[Match]
Profiles=liveiso
Distribution=fedora

# From https://github.com/Zeglius/titanoboa/blob/revamp-pr/examples/zirconium/src/build.sh on commit message

[Output]
# isobuild's root is a chroot
Format=directory
