[Content]
Packages=
    bootc
    dracut-live
    fuse-overlayfs
    livesys-scripts
    readymade
    skopeo
    systemd-boot-unsigned

RemoveFiles=
    /etc/localtime
    /usr/lib/systemd/system-preset/01-homebrew.preset
    /usr/lib/systemd/system-preset/01-zirconium.preset
