[Match]
Profiles=asahi
Distribution=fedora
Architecture=arm64

[Build]
SandboxTrees=../../repos/fedora-asahi-remix-hotfixes.repo:/etc/yum.repos.d/fedora-asahi-remix-hotfixes.repo
SandboxTrees=../../repos/group_asahi-fedora-remix-branding.repo:/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:group_asahi:fedora-remix-branding.repo
SandboxTrees=../../repos/group_asahi-fedora-remix-scripts.repo:/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:group_asahi:fedora-remix-scripts.repo
SandboxTrees=../../repos/group_asahi-kernel.repo:/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:group_asahi:kernel.repo
SandboxTrees=../../repos/group_asahi-mesa.repo:/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:group_asahi:mesa.repo
SandboxTrees=../../repos/group_asahi-u-boot.repo:/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:group_asahi:u-boot.repo

[Distribution]
Repositories=fedora-asahi-remix-hotfixes
Repositories=copr:copr.fedorainfracloud.org:group_asahi:fedora-remix-branding
Repositories=copr:copr.fedorainfracloud.org:group_asahi:fedora-remix-scripts
Repositories=copr:copr.fedorainfracloud.org:group_asahi:kernel
Repositories=copr:copr.fedorainfracloud.org:group_asahi:mesa
Repositories=copr:copr.fedorainfracloud.org:group_asahi:u-boot

[Content]
RemovePackages=
    kernel
    kernel-core
    kernel-modules-extra

Packages=
    alsa-ucm-asahi
    asahi-platform-metapackage
    asahi-repos
    fedora-asahi-remix-scripts
    tiny-dfr
    grub2-efi-aa64-modules
    uboot-images-armv8
    asahi-fwupdate
    dracut-asahi
    update-m1n1
    aajohan-comfortaa-fonts
