# https://github.com/bootc-dev/bootc/issues/2339

[Match]
Release=44
Architecture=x86-64

[Content]
Packages=
    https://kojipkgs.fedoraproject.org//packages/bootc/1.16.2/1.fc44/x86_64/bootc-1.16.2-1.fc44.x86_64.rpm
