# https://github.com/bootc-dev/bootc/issues/2339

[Match]
Release=44
Architecture=arm64

[Content]
Packages=
    https://kojipkgs.fedoraproject.org//packages/bootc/1.16.2/1.fc44/aarch64/bootc-1.16.2-1.fc44.aarch64.rpm
