# https://github.com/ostreedev/ostree/issues/3635
# for now we're downgrading it while we're waiting for new builds in fedora repos

[Match]
Release=44
Architecture=x86-64

[Content]
Packages=
    https://kojipkgs.fedoraproject.org//packages/ostree/2026.2/1.fc44/x86_64/ostree-2026.2-1.fc44.x86_64.rpm
    https://kojipkgs.fedoraproject.org//packages/ostree/2026.2/1.fc44/x86_64/ostree-libs-2026.2-1.fc44.x86_64.rpm
